### ISSUE TITLE
Documentation of CurrencyHistory Rates

### ISSUE THREAD

**Issue by 3DExtended** [dshe/YahooQuotesApi#1]
I recently found this really helpful API and was playing around with the examples given in the readme.
I was wondering if you could give me a little explanation on how to use the values given in the CurrencyHistory example. 

I was expecting in the last example (see code below) that it would give me a decimal (or double as stated in your code) which symbolizes the conversion rates from USD to EUR. However, what I have found are pretty small numbers (Rate = 0.00010785159620362382 as of 24.03.2020) which I can not correlate to any information. Could you clarify what those rates are and if it is possible to use your API to get the current conversion rates from one currency to another?

Thank you for your help!

The code that I am referring to (taken from the readme file):
```c#
CurrencyHistory CurrencyHistory = new CurrencyHistory();

string currency     = "EUR";
string baseCurrency = "USD";

List<RateTick> rates = await CurrencyHistory
    .FromDate(new LocalDate(2010,1,1))
    .GetRatesAsync(currency, baseCurrency);

Assert.True(rates[0].Rate > 0);
```

**Comment by dshe** [comment]
Thank you for your comment and sorry for the delay.

There is a new version of YahooQuootesApi available.

Please try:

var yahooQuotes = new YahooQuotesBuilder().Build();
var security = await yahooQuotes.GetAsync("USDEUR=X");
var price = security.RegularMarketPrice;
