### ISSUE TITLE
Feature Request: Add Company Financial Data like Balance Sheet, Income Statement & Cashflow

### ISSUE THREAD

**Issue by shailendersindhu** [dshe/YahooQuotesApi#11]
The project is very good, Thanks for all your hard work. It will help a lot of people.
I have one feature request for you if possible. Can you extend the API to download Company Financial Data like Balance Sheet, Income Statement & Cashflow. Its already available on Yahoo e.g.

https://finance.yahoo.com/quote/AAPL/balance-sheet?p=AAPL

This feature is not available in any existing project. Thanks again.

**Comment by dshe** [comment]
Please try version 5.3:

`Result<JsonProperty[]> result = 
	await YahooQuotes.GetModulesAsync("TSLA", new[] { "assetProfile", "defaultKeyStatistics" });`

[https://yahooquery.dpguthrie.com/guide/ticker/modules/](url)
