### ISSUE TITLE
401 (Unauthorized) - This issue start happening again.... (As of now)

### ISSUE THREAD

**Issue by E-Moses** [dshe/YahooQuotesApi#13]
https://github.com/dshe/YahooQuotesApi/issues/12

401 (Unauthorized).

**Comment by sachatomey** [comment]
Yup - ditto.

**Comment by bdleedy** [comment]
I've just started to use this and everything was working great yesterday and today I'm running into issues and decided to check here. HOW are you pulling this error forward?

I only get System.AggregateException: 'One or more errors occurred. (quoteResponse)' with no clue that it's based on a 401 error.

**Comment by E-Moses** [comment]
Last time (https://github.com/dshe/YahooQuotesApi/issues/12) we waited for few days until Yahoo fixed the issue.
I don't know if its the same issue now as last time (it has the same symptoms as last time, so I assume its the same issue).

I will be thankful to dshe-DavidS if he can check the issue.

**Comment by E-Moses** [comment]
Still not working.... :(

**Comment by E-Moses** [comment]
Is it currently working for someone?

**Comment by sachatomey** [comment]
No, same behaviour.

**Comment by nsulikowski** [comment]
I see the same problem. Has Yahoo changed its terms?

**Comment by E-Moses** [comment]
We really don't know what/where is the problem.
We all waiting for dshe-DavidS to check and respond.
We still haven't heard from him. :(

**Comment by sachatomey** [comment]
I believe the issue is in the Yahoo side as a deployed solution (without change) started demonstrating this behaviour.

**Comment by kyi87** [comment]
Maybe there should be some cookies set. I have something in my mind, that this was a problem with an other yahoo api client.

**Comment by E-Moses** [comment]
> I would be happy if the api worked because I'm using this in a uni project and i don't have time for changes.

100% with you. Same for me!

**Comment by rwb196884** [comment]
Is there a workaround?

**Comment by E-Moses** [comment]
> Is there a workaround?

not that we know of.
we still waiting for respond from dshe-DavidS.

**Comment by kyi87** [comment]
I created a pull request (https://github.com/dshe/YahooQuotesApi/pulls) to configure the API-Version. 
Its working fine with API version 6 -> all tests passed.

 Is there a need to use v7?

**Comment by nsulikowski** [comment]
awesome. It is a good feature to have regardless!

**Comment by E-Moses** [comment]
> I created a pull request (https://github.com/dshe/YahooQuotesApi/pulls) to configure the API-Version. Its working fine with API version 6 -> all tests passed.
> 
> Is there a need to use v7?

very Nice.
Thank you for the effort.
But its still a kind of workaround - eventually, you will need to work with the latest version Yahoo.

Can  version

**Comment by E-Moses** [comment]
Can I find this version in the Nugat repository (In Visual Studio)?

**Comment by kyi87** [comment]
Not yet. The author has first to accept the pull request. But in the meantime you can clone the repository and add it as project to your solution and bind it as project reference to your projects. Thats what did.

**Comment by dshe** [comment]
You can try version 5.3.4. 

Thanks to kyi87!

**Comment by E-Moses** [comment]
I will try it today.
Thank you guys!

**Comment by sachatomey** [comment]
Version 5.3.4 via the NuGet Package Manager worked for me.
Thanks all !

**Comment by E-Moses** [comment]
Works fine.
thanks!
