### ISSUE TITLE
Error accessing pricehistory

### ISSUE THREAD

**Issue by kyi87** [dshe/YahooQuotesApi#18]
I get an error accessing the pricehistory since recently:

**Error (german):**
_System.Net.Http.HttpRequestException: 'Der angeforderte Name ist gültig, es wurden jedoch keine Daten des angeforderten Typs gefunden. (fc.yahoo.com:443)'_

**Error (englisch -> my translation):** 
_The requested name is valid, but no data of the requested type was found_

My code:
```
          var dateNow = DateTime.Now.ToUniversalTime();
          var dateTimeStart = dateNow.AddDays(-100);
          var dateStart = Instant.FromDateTimeUtc(dateTimeStart);
          YahooQuotes yahooQuotes = new YahooQuotesBuilder()
              .WithHistoryStartDate(dateStart)
              .WithPriceHistoryFrequency(frequency: Frequency.Daily)
              .Build();

          var security = yahooQuotes.GetAsync("MBG.DE", Histories.PriceHistory).GetAwaiter().GetResult();
```

Is anyone experiencing the same problem? 

Thanks.

**Comment by leacasas** [comment]
Tested it with several tickers, including the mentioned in the issue, and I did not observe the same. it all looks fine to me. I see the complete ticker data also in Yahoo Finance. Maybe it was something temporary?

**Comment by Morcatko** [comment]
I am having the same issue since I update to latest nuget version.
English error is:
```
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (fc.yahoo.com:443)
```

**Comment by Morcatko** [comment]
I did some experiments and my guess is Yahoo is blocking access based on location.
I am connecting from Czech Republic. The OP is from Germany (I assume) and we both have the same error.

When I go to `https://fc.yahoo.com/` in a browser (library does this to get some cookie) I get a connection error, however when I use UK VPN I get 404 with set-cookies header that is probably needed for further querries - https://github.com/dshe/YahooQuotesApi/blob/c2ed5d8bcd8d762013426c7e37e0a10cb7b51cc2/YahooQuotesApi/Crumb/YahooCrumb.cs#L48-L53
