### ISSUE TITLE
API stop working again: Exception at GetCookieAndCrumb()

### ISSUE THREAD

**Issue by E-Moses** [dshe/YahooQuotesApi#19]
Maybe the CookieAndCrumb expired?
What can we do to fix it?

The returned exception in .Net:
System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests). at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() at YahooQuotesApi.Crumb.YahooCrumb.GetCookieAndCrumb(CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Crumb\YahooCrumb.cs:line 72 at YahooQuotesApi.YahooSnapshot.GetElements(Symbol[] symbols, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 80 at YahooQuotesApi.YahooSnapshot.Producer(Symbol[] symbols, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 45 at YahooQuotesApi.SerialProducerCache`2.Get(HashSet`1 keys, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Utilities\SerialProducerCache.cs:line 47 at YahooQuotesApi.YahooSnapshot.GetAsync(HashSet`1 symbols, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 36 at YahooQuotesApi.Quotes.GetSecuritiesAsync(HashSet`1 symbols, Histories historyFlags, Symbol historyBase, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Core\Quotes.cs:line 63 at YahooQuotesApi.Quotes.GetAsync(HashSet`1 symbols, Histories historyFlags, Symbol historyBase, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Core\Quotes.cs:line 42 at YahooQuotesApi.YahooQuotes.GetAsync(IEnumerable`1 symbols, Histories historyFlags, String historyBase, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\YahooQuotes.cs

**Comment by E-Moses** [comment]
Start working again now.

**Comment by E-Moses** [comment]
This issue start happening again now. API not working.

**Comment by kaposhkin** [comment]
Same issue here. Looks like the request to get a crumb fails with 429 status code.

As a temporary workaround I manually copy cookies and crumb and set them in the method GetCookieAndCrumb. 

As a reference https://stackoverflow.com/questions/76065035/yahoo-finance-v7-api-now-requiring-cookies-python

**Comment by E-Moses** [comment]
As a temporary workaround its fine, but a permanent fix for this issue is needed - its happening every couple of days...

**Comment by E-Moses** [comment]
@leacasas or @dshe - can you handle the issue PLEASE...

**Comment by E-Moses** [comment]
> As a temporary workaround I manually copy cookies and crumb and set them in the method GetCookieAndCrumb.

@kaposhkin  can you give us more details on how to do it?
 What cookies did you copy? from where? to where? have you change their content - and if so what have you change?

**Comment by kaposhkin** [comment]
1. Clone this repo to your machine
2. Attach to your project
3. Find method GetCookieAndCrumb and override it:

```
    public async Task<(IEnumerable<string>, string)> GetCookieAndCrumb(CancellationToken ct)
    {
        // Get from cache
        if (StoredCookieAndCrumb != default((IEnumerable<string>, string)))
            return StoredCookieAndCrumb;

        var cookie = new List<string>()
        {
            "ADD_COOKIES_HERE"
        };

        string crumb = "ADD_CRUMB_HERE";

        if (string.IsNullOrEmpty(crumb))
            throw new HttpRequestException($"Could not generate crumb from {YahooGetCrumbUrl} for cookie {cookie.First(x => x.StartsWith("A3", StringComparison.OrdinalIgnoreCase))}");

        StoredCookieAndCrumb = (cookie, crumb);

        return StoredCookieAndCrumb;
    }
```

5. Go here https://fc.yahoo.com/ and grab cookies
6. Go here and get crumb https://query2.finance.yahoo.com/v1/test/getcrumb

**Comment by leacasas** [comment]
Added new PR https://github.com/dshe/YahooQuotesApi/pull/20
