### ISSUE TITLE
Short Interest on the Yahoo statistics page.

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [dshe/YahooQuotesApi#2]
Is the short interest on another API? 

https://finance.yahoo.com/quote/TSLA/key-statistics?p=TSLA

Share Statistics

Avg Vol (3 month) 3 | 24.61M
Avg Vol (10 day) 3 | 27.42M
Shares Outstanding 5 | 1B
Implied Shares Outstanding 6 | N/A
Float 8 | 818.15M
% Held by Insiders 1 | 19.18%
% Held by Institutions 1 | 42.39%
Shares Short (Nov 15, 2021) 4 | 25.7M
Short Ratio (Nov 15, 2021) 4 | 0.76
Short % of Float (Nov 15, 2021) 4 | 3.15%
Short % of Shares Outstanding (Nov 15, 2021) 4 | 2.56%
Shares Short (prior month Oct 14, 2021) 4 | 30.34M

**Comment by dshe** [comment]
At this time, YahooQuotesApi obtains snapshot data from "query2.finance.yahoo.com/v7/finance/quote" where statistics such as short interest are not provided.
