### ISSUE TITLE
Requests timing out across the board

### ISSUE THREAD

**Issue by GelLiNN** [dshe/YahooQuotesApi#23]
Hello, I've been using this for a few weeks as a replacement for another broken YahooFinance API that I used before.  All the requests worked great yesterday giving me quotes and price history for any given symbol, but today I wasn't able to get anything...

I went ahead and dug into the issue and it is happening at the step where you make a request to https://fc.yahoo.com/ to obtain a cookie.  I replicated this request in Postman and it was giving me 502 service unavailable.  So there is a chance something else is happening.  I googled around and did not see any kind of reference about these API URLs anywhere other than other 3rd party projects.  Can you take a look and see what's going on?

Thanks a bunch!

**Comment by dshe** [comment]
I made some changes which seem to fix the problem. Please try the new release.

Thank you for reporting the problem.

**Comment by endeffects** [comment]
I had the same problem, after the update i'm receiving no more quotes:

await yahoo.GetAsync($"6A=F", Histories.PriceHistory, "", cancellationToken)

**Comment by emoreau99** [comment]
Hi

I am too a user of the other YahooFinanceApi.

I just downloaded your code and tried to run the SnapShot test and still get an error: 
![image](https://github.com/dshe/YahooQuotesApi/assets/6817203/a9a408b0-1d00-4a9c-b23e-20ae457352e5)

You don't get this issue?
