### ISSUE TITLE
Missing Future Quotes

### ISSUE THREAD

**Issue by endeffects** [dshe/YahooQuotesApi#24]
With the latest update I don't receive any future quotes anymore:

await yahoo.GetAsync($"6A=F", Histories.PriceHistory, "", cancellationToken)

**Comment by zeabee** [comment]
I am having the same issue (no quotes) after the update:
   await yahooQuotes.GetAsync(ticker, Histories.PriceHistory)

**Comment by izzeww** [comment]
I'm not getting it to work at all, had it working a few days ago.

**Comment by zeabee** [comment]
I am still having the same issue (no quotes) after the update (v5.5.3)

**Comment by dshe** [comment]
Does version 5.3.3 always fail with "No useful cookies found"?

Did version 5.3.2 also always fail?

Can you please let me know the cookies you receive from the method "GetCookies()". What is the logger output from: 

      Logger.LogTrace(message: "GetCookieAndCrumb: received these cookies ... ?

**Comment by zeabee** [comment]
I received the below errors:
- Update 5.5.2 failed with  "One or more errors occurred. (Sequence contains no matching element)"
- Update 5.5.3 failed with "One or more errors occurred. (No useful cookies found.)"

On the debug output I am way out of my depth but if I try to get cookie info in catch statement after getYahooStockDataAsync(symbol) for 5.5.3 I get:

ookie:
AS = v=1&s=tiJC78kU&d=A65746c05|CUrykM7.2SoTw4QZbnmYEHM0Y.V3pBTP6sNdn9PYZg7MoDraVzeYP5ZEvvKBUZAhYmDAZG5Nx6MtMPbgHeAHDMK9VqELg3mJlCGGIMA2kaROG3tKmG8gpt7tAUVKX2PK3eigULE_Tzs1LYluTNlQniBr7027LBrNOqgEZ3NW..9pzSmxvISC51pO3kzlpHSaedjNtHynxPalgzjg.khEHiDkzjrEzDy6Rk944ihahz7yhM2vqVjpbHqKJtaa_hjMuhHTnXZoZwawXjnHNkaOY3o2anrtSvN5EbVyG8cIGiwGJzxNVsUJzgBAKY4xKX189nsu4bKaKnrMHzEXZe9n4x28l7yFZAqR9j8LzJB5YnxjDYc.USi6FX2cMpDk1H2Q0kdHoCEhiEHa.PNDckiFN3MVQxE11e2K5mExhY0tpzl8Mwn.zx.mvmNssEMETYjWbMtFk_gbIBR5WpLNn_CBKXuP4RKEyGQRNaqqLqUXXlYKQkvHKyWBOfZD63nGnXwrEk_HQF74opwy1vETHyTS3JizahB41RJXhhKr8zyeLj0OUKMJPZXBB2okpZVK0YL8Kz7X1IkFDp_3BdHEWnmy1ZQ4pBbyhq1E_sQI7RktkIK5ztsxzTcGX6PN4GzviOpZtVD7PSSkrt57ROKOLrT6UUilC_pPa_0P0EyneTSVbY_xSyYG0RwrWazwu8MgKICqaN2_Ve539rjsJ2O7JZ4ZP.WwQLjPS_lrwOO.jT.XHeOqRmnUNrUc~A
Domain: login.yahoo.com
Path: /
Port:
Secure: True
When issued: 08/12/2023 13:30:45
Expires: 01/01/0001 00:00:00 (expired? False)
Don't save: False
Comment:
Uri for comments:
Version: RFC 2965

Not sure if this is helpful!?

**Comment by lcapka** [comment]
Raw lines from the log:

```
GetCookieAndCrumb: received these cookies(1): 
AS=v=1&s=dQBRFF5z&d=A6574c38f|I_7K1Tr.2SqgS0bI5GsuKiv.kpJo8US1IY_Oc7NJ_JIyJ7YLYNYyFa5yBAbBR1PbClGb0.u5B9iceJd7M.Ys9.9MTVy.nBsOf2KNew9rNkbgI4p.HEjTmVnU5uF5OZQci2dFj_BKRcQ9rCCR3AoCcE3tgSTA_pZs283Tppj8B3eS_iPzAROiI2YQb7MOP3S99ZgqpE_yxAqhdW061euoz6mGk9IWCGmFrS3jGhPPllECuqh8keatIu_eHwAkTnkRQ9a_Q8SU2Wrkmo4z3z0Ss.3ca1V1QGNpO1OuaBoIG2POi8BV8cE_UyTpuMBBpzqgfa88uMcbLjawn1IJRB1Ou_CGXKKDqVnZV0RcIOgGd54LJJBRRTJkew5UvlhXEpURV0w93slUmMccr2cX910bdwGqxhLRiw5JFvsH6hiRJmYR9jLitTNweq9TBakglPC47JmwTjOLHkyaKq6a7mf4bj_89qNJq.rTAalGgss7cW8ioATrqoykofjhn6WjcenCzCeXbgdUj7RYobt0guA6LxPan5N8N2I70.zjcBk46F_Jy6.9hjWo.ogRQ3JmrHoxKYVo.HLUE1ktuKf0uy_baY3.JP2x70RDMzNBVqYRjQJXYw1JYAg3VCk_LrCdXvp7BlkOdkA.l4PWPEkzcHpGG_j6YsJtQtbqCAVH.SmGF0f_t7HbbnfpbmPS.Vj4vCu903_qo6tayzLoVyg7gesEwV8-~A; path=/; domain=login.yahoo.com; secure; HttpOnly
```

**Comment by dshe** [comment]
Thank you @zeabee and @lcapka. It seems you are not receiving the necessary cookies from "https://login.yehoo.com". New release 5.5.4 has an option to change the Uri for cookies and crumb. I suggest you try the following:
```
     YahooQuotes yahooQuotes = new YahooQuotesBuilder()
            .WithCookieUri(new Uri("https://finance.yahoo.com/"))
            .Build();
```

**Comment by zeabee** [comment]
Trying with v5.5.4 and the option (.WithCookieUri(new Uri("https://finance.yahoo.com/"))) I get the following error:

"One or more errors occurred. (Set-Cookie header was not present in the response from https://finance.yahoo.com/.)"

**Comment by endeffects** [comment]
Same for me. I tried different urls but i received the same errors. Also previous versions didn't work for me either.

**Comment by endeffects** [comment]
Maybe the issue is related to the tls version used by the client. I have noticed that it works by running fiddler and the chrome browser but it fails with net client.

**Comment by endeffects** [comment]
I tried to debug the issue and it seems like that there is a blocking consent page which delivers the required cookies. maybe this is an EU issue only?

**Comment by zeabee** [comment]
Interesting observation @endeffects. To follow on from that: below shows that code works from US based server (without the option in v5.5.4). Not sure if there is a fix that can be applied @dshe.

When I ran version 5.5.3
 - Local client (UK) - error "No useful cookies found."
 - Through US-based VPN - worked fine in general but a few (out of 87 tickers) errors "Response status code does not indicate success: 500 (Internal Server Error)"  

When I ran version 5.5.4 with .WithCookieUri(new Uri("https://finance.yahoo.com/")) option set
 - Local client (UK) - error "Set-Cookie header was not present in the response from https://finance.yahoo.com/."
 - Through US-based VPN - error "Set-Cookie header was not present in the response from https://finance.yahoo.com/."

When I ran version 5.5.4 without .WithCookieUri(new Uri("https://finance.yahoo.com/")) option
 - Local client (UK) - error "No useful cookies returned in the response from https://login.yahoo.com/."
 - Through US-based VPN - worked fine

**Comment by endeffects** [comment]
I also tried to change the AcceptLanguage Header to en-US but this doesn't work. So they use some geoip tracking to restrict the access.

**Comment by dshe** [comment]
The default CookieUri is "https://login.yahoo.com". This seems to work fine for many users, including me in Malaysia.

The original CookieUri "https://fc.yahoo.com" still seems to work, but with a delay of more than 30 seconds.

I read that some other yahoo finance projects had successfully used CookieUri "https://finance.yahoo.com/". But that doesn't seem to work for you.

**Comment by dshe** [comment]
@endeffects Your code, although complicated, seems to work in the EU. That must have taken a significant effort to figure out. Thank you! Sometimes, however, after your code, there is a failure to get the crumb. I would appreciate if you could look at the source code and rebuild the library to test.

**Comment by lcapka** [comment]
Hi, is there any plan to release the fix?

**Comment by lcapka** [comment]
All that redirect magic with POST to confirm cookies policies implemented in 5.5.5 seems to be working well in EU. Well done guys.

**Comment by twestosaurus** [comment]
Hi, maybe I'm missing something here - but it seems 5.5.5. is missing the .WithCookiUri option (contrary to 5.5.4.). Anyways thanks for this great package!

**Comment by lcapka** [comment]
Hi @twestosaurus, you are right. That method has been removed as it's not needed in 5.5.5 implementation.

**Comment by twestosaurus** [comment]
Hi, ok - with 5.5.5. I'm getting "Did not receive crumb from https://query2.finance.yahoo.com/v1/test/getcrumb using cookies." from EU. Not really sure if there could be an error in my code though.

**Comment by izzeww** [comment]
Any update on this? Any way to get it to work for EU people?

**Comment by twestosaurus** [comment]
Hi, for me it's still really weird: it worked now for me exactly once - without changing anything in my code - and now I'm running again into this exception.

**Comment by izzeww** [comment]
> Hi, for me it's still really weird: it worked now for me exactly once - without changing anything in my code - and now I'm running again into this exception.

I don't know why this is, but for me with .NET 6.0 it's like 50/50 if it works or not, while with .NET 7.0 or .NET 8.0 it works 100% of the time. So maybe update your version of .NET and it should fix it.

**Comment by twestosaurus** [comment]
> > Hi, for me it's still really weird: it worked now for me exactly once - without changing anything in my code - and now I'm running again into this exception.
> 
> I don't know why this is, but for me with .NET 6.0 it's like 50/50 if it works or not, while with .NET 7.0 or .NET 8.0 it works 100% of the time. So maybe update your version of .NET and it should fix it.

Indeed with .NET 8 it suddenly works again, thanks!

**Comment by izzeww** [comment]
It should probably either be noted in the project readme that it's not compatible with .NET 6.0 (only 7.0 and above) or fix it so it is compatible with .NET 6.0. Currently it says it's compatible with .NET 6.0 when it really isn't (at least for EU users).

**Comment by dshe** [comment]
Please try with the new version 5.5.6 and let us know if there are any problems remaining.

**Comment by zeabee** [comment]
@dshe v5.5.6 works for me (in EU), but as stated above with .NET 7.0 (not 6.0). Thanks for persevering.

**Comment by dshe** [comment]
YahooQuotesApi is based on NET 6 so it should not require NET 7.  Is your application using MAUI?

- Try opening the YahooQuotesApi solution on your machine and running the tests.
- Try running the tests using a VPN (such as the free Proton VPN), with a connection to USA, then Europe.
- Try disabling HttpResilience as follows:
```
YahooQuotes yahooQuotes = new YahooQuotesBuilder()
        .WithoutHttpResilience()
        .Build();

```
