### ISSUE TITLE
Adding support for fundamental data

### ISSUE THREAD

**Issue by izzeww** [dshe/YahooQuotesApi#25]
This library doesn't appear to support fundamental data from Yahoo Finance (https://query1.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/{ticker}). Other Yahoo Finance libraries, like yfinance for python, supports this feature. I think it would be nice if it was added. I suck at coding so I can't add it however.

**Comment by dshe** [comment]
YahooQuotesApi can retrieve various "modules", some of which provide fundamental data. For example:
`   Result<JsonProperty[]> result = await YahooQuotes.GetModulesAsync("TSLA", "AssetProfile");`

Please see:
`   YahooQuotesApi.Tests/Tests/ModulesTests.cs `
