### ISSUE TITLE
Asking multiple 

### ISSUE THREAD

**Issue by borovanhout** [dshe/YahooQuotesApi#3]
First of all, thanks a bunch for this API! I'm having a great time using it. However, there is one issue that I'm having: I can't seem to get any info for multiple tickers at the same time. Do you have any idea what could be causing the issue? This is (a simplified version of) the function that I'm using to call the API:
```
        public async Task<Dictionary<string,Security>> GetStockPrices(string[] tickers)
        {
            Dictionary<string, Security> securities = await yahooQuotes.GetAsync(tickers);
        }
```
However, securities never contains anything, the function always just skips to the next line. Do you have any idea why this could happen?

Just for extra info, this is how I'm calling the function. The application is a WinForms app running on 6.0
```
        private void button1_Click(object sender, EventArgs e)
        {
               var priceInfo = GetStockPrices(new string[] { "TSLA","AAPL"});
        }
```
Just for extra info, this is what returned to me:
![image](https://user-images.githubusercontent.com/80459499/145445431-0e84bd5d-127b-426b-9ead-46570c367a1d.png)

**Comment by dshe** [comment]
GetStockPrices() is an asynchronous method. You must await it:
```csharp
      var priceInfo = await GetStockPrices(new string[] { "TSLA","AAPL"});}
```

**Comment by borovanhout** [comment]
Even with the await, I get the same response

**Comment by dshe** [comment]
```csharp
using YahooQuotesApi;
namespace WinFormsApp1;

public partial class Form1 : Form
{
    YahooQuotes yahooQuotes = new YahooQuotesBuilder().Build();

    public Form1()
    {
        InitializeComponent();
    }

    public async Task<Dictionary<string, Security>> GetStockPrices(string[] tickers)
    {
        return await yahooQuotes.GetAsync(tickers);
    }

    private async void button1_Click(object sender, EventArgs e)
    {
        var priceInfo = await GetStockPrices(new string[] { "TSLA", "AAPL" });
        button1.Text = priceInfo["TSLA"].RegularMarketPrice.ToString();
    }
}
```

**Comment by borovanhout** [comment]
Ah, so it did work the entire time... Visual studio is just not able to show me the info while debugging... I wish I had known this before... So much time wasted lol.

Thank you very much for your response, was thinking I had some sort of weird issue.
