### ISSUE TITLE
Historical Quote Streaming is not working

### ISSUE THREAD

**Issue by joy151280** [dshe/YahooQuotesApi#5]
Historical Quote Streaming has stooped working with Exception "InvalidOperationException: YahooHistory: failure to reset HttpClient."

**Comment by E-Moses** [comment]
yep, same for me.

**Comment by dshe** [comment]
Please try version 5.1.

**Comment by joy151280** [comment]
Thanks. Now Historical streaming is working perfectly.

**Comment by dshe** [comment]
The issue was fixed by simply not sending cookies to Yahoo Finance.
