### ISSUE TITLE
Response status

### ISSUE THREAD

**Issue by ymilad** [dshe/YahooQuotesApi#6]
I got response message 
"Response status code does not indicate success: 401 <Unauthorized>"

**Comment by MarkusFank** [comment]
I have the same problem. For example the symbol "MSFT" delivers most of the time a 401, sometimes it works. Same with a lot of other symbols

**Comment by dshe** [comment]
An HTTP status code 401 (unauthorized) received from Yahoo Finance probably indicates that the request has been throttled. It has been suggested that unauthorized calls to Yahoo Finance are limited to 2,000/hour/IP address.

**Comment by Panache1** [comment]
I think the Yahoo Finance algorithm is a bit more complicated than that, but if you pause periodically, 401 shouldn't be a problem.

**Comment by dshe** [comment]
A future version of YahooFinanceApi will support rate-limiting.
