### ISSUE TITLE
One test fails... 

### ISSUE THREAD

**Issue by kosuodhmwa** [dshe/YahooQuotesApi#8]
Fresh installation of Win10 x64 Pro with Visual Studio Community 2022... 

![image](https://user-images.githubusercontent.com/24782840/189320205-41b3d9f1-a653-496f-9eea-95af439a5ace.png)

**Comment by dshe** [comment]
The test fails for TSLA because there was a 3 for 1  stock split on August 17, and the test did not take this into account.
